//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancDelTemps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancDelTemps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by author.
        /// </summary>
        public static string ButtonFilterAuthor {
            get {
                return ResourceManager.GetString("ButtonFilterAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by category.
        /// </summary>
        public static string ButtonFilterCategory {
            get {
                return ResourceManager.GetString("ButtonFilterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by date created.
        /// </summary>
        public static string ButtonFilterDateCreated {
            get {
                return ResourceManager.GetString("ButtonFilterDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by date finished.
        /// </summary>
        public static string ButtonFilterDateFinished {
            get {
                return ResourceManager.GetString("ButtonFilterDateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase the filter.
        /// </summary>
        public static string ButtonFilterDelete {
            get {
                return ResourceManager.GetString("ButtonFilterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by description.
        /// </summary>
        public static string ButtonFilterDescription {
            get {
                return ResourceManager.GetString("ButtonFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by e-mail.
        /// </summary>
        public static string ButtonFilterEmail {
            get {
                return ResourceManager.GetString("ButtonFilterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by full name.
        /// </summary>
        public static string ButtonFilterFullName {
            get {
                return ResourceManager.GetString("ButtonFilterFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by state.
        /// </summary>
        public static string ButtonFilterState {
            get {
                return ResourceManager.GetString("ButtonFilterState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by title.
        /// </summary>
        public static string ButtonFilterTitle {
            get {
                return ResourceManager.GetString("ButtonFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string CheckboxRemember {
            get {
                return ResourceManager.GetString("CheckboxRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Post.
        /// </summary>
        public static string DeletePost {
            get {
                return ResourceManager.GetString("DeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string GenreMen {
            get {
                return ResourceManager.GetString("GenreMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string GenreOther {
            get {
                return ResourceManager.GetString("GenreOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string GenreWoman {
            get {
                return ResourceManager.GetString("GenreWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name.
        /// </summary>
        public static string GridAuthorName {
            get {
                return ResourceManager.GetString("GridAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string GridCategory {
            get {
                return ResourceManager.GetString("GridCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string GridDateCreated {
            get {
                return ResourceManager.GetString("GridDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date finished.
        /// </summary>
        public static string GridDateFinished {
            get {
                return ResourceManager.GetString("GridDateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GridDescription {
            get {
                return ResourceManager.GetString("GridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string GridEmail {
            get {
                return ResourceManager.GetString("GridEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string GridGenre {
            get {
                return ResourceManager.GetString("GridGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string GridLastName {
            get {
                return ResourceManager.GetString("GridLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string GridLocation {
            get {
                return ResourceManager.GetString("GridLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GridName {
            get {
                return ResourceManager.GetString("GridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register date.
        /// </summary>
        public static string GridRegisterDate {
            get {
                return ResourceManager.GetString("GridRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised.
        /// </summary>
        public static string GridRevised {
            get {
                return ResourceManager.GetString("GridRevised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GridTitle {
            get {
                return ResourceManager.GetString("GridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title post.
        /// </summary>
        public static string GridTitlePost {
            get {
                return ResourceManager.GetString("GridTitlePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username/password.
        /// </summary>
        public static string LoginErrorText {
            get {
                return ResourceManager.GetString("LoginErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string TextboxAuthor {
            get {
                return ResourceManager.GetString("TextboxAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TextboxCategory {
            get {
                return ResourceManager.GetString("TextboxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TextboxDescription {
            get {
                return ResourceManager.GetString("TextboxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string TextboxFullName {
            get {
                return ResourceManager.GetString("TextboxFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TextboxPassword {
            get {
                return ResourceManager.GetString("TextboxPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TextboxTitle {
            get {
                return ResourceManager.GetString("TextboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string TextboxUsername {
            get {
                return ResourceManager.GetString("TextboxUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a date.
        /// </summary>
        public static string TextDatePicker {
            get {
                return ResourceManager.GetString("TextDatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORIES.
        /// </summary>
        public static string TitleCategories {
            get {
                return ResourceManager.GetString("TitleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACTS.
        /// </summary>
        public static string TitlePacts {
            get {
                return ResourceManager.GetString("TitlePacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTS.
        /// </summary>
        public static string TitlePosts {
            get {
                return ResourceManager.GetString("TitlePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORTS.
        /// </summary>
        public static string TitleReports {
            get {
                return ResourceManager.GetString("TitleReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERS.
        /// </summary>
        public static string TitleUsers {
            get {
                return ResourceManager.GetString("TitleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
    }
}
