//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancDelTemps.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public int Id_Ban { get; set; }
        public System.DateTime ban_date { get; set; }
        public Nullable<System.DateTime> ban_finish_date { get; set; }
        public int UserId_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
