//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancDelTemps.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pact
    {
        public int Id_Pact { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_finished { get; set; }
        public string description { get; set; }
        public string title { get; set; }
        public int Posts_Id_Post { get; set; }
        public int Reports_Id_Report { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Report Report { get; set; }
    }
}
